services:
    php:
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - stack.env # Environment variables for the PHP service in portainer

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        networks:
            - joeap_network

    nginx:
        env_file:
            - stack.env # Environment variables for the Nginx service in portainer

volumes:
    mysql_data:
        name: joeap_mysql_data
